import { apiRequest } from '../../api/client';

export interface DiscoverableCandidate { user_id: string; city: string; headline: string; candidate_type: 'certified_educator' | 'student'; institution: string | null; program: string | null; expected_graduation_date: string | null; onboarding_completed_at: string; certification_type: string | null; certification_verification_status: 'unverified' | 'pending' | 'verified' | 'rejected'; certification_provenance: 'manual' | 'local_ocr' | null; certification_candidate_confirmed_at: string | null; discoverable: true; experience_count: number; updated_at: string; }
export interface MarketplaceInterest { id: string; profile_user_id: string; job_id: string; status: 'requested'; message: string | null; created_at: string; }
export interface InterviewRequest { id: string; application_id: string; scheduled_at: string; location_or_link: string; status: 'requested'; }
export interface CredentialNotification { id: string; credential_id: string; candidate_user_id: string; candidate_name: string; previous_certificate_type: string | null; certificate_type: string; read_at: string | null; created_at: string; }
export class MarketplaceApiError extends Error { constructor(message: string) { super(message); this.name = 'MarketplaceApiError'; } }
const object = (value: unknown, label: string): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new MarketplaceApiError(`The server returned an invalid ${label}.`); return value as Record<string, unknown>; };
const string = (value: unknown, label: string) => { if (typeof value !== 'string' || !value.trim()) throw new MarketplaceApiError(`The server returned an invalid ${label}.`); return value; };
const nullableString = (value: unknown, label: string) => value == null ? null : string(value, label);
const oneOf = <T extends string>(value: unknown, allowed: readonly T[], label: string): T => { const result = string(value, label); if (!allowed.includes(result as T)) throw new MarketplaceApiError(`The server returned an unsupported ${label}.`); return result as T; };
const nullableOneOf = <T extends string>(value: unknown, allowed: readonly T[], label: string): T | null => value == null ? null : oneOf(value, allowed, label);
export function parseDiscoverableCandidate(value: unknown): DiscoverableCandidate { const row = object(value, 'discoverable candidate'); if (row.discoverable !== true || !Number.isInteger(row.experience_count) || Number(row.experience_count) < 0) throw new MarketplaceApiError('The server returned an invalid discoverable candidate summary.'); return { user_id: string(row.user_id, 'marketplace user id'), city: string(row.city, 'candidate city'), headline: string(row.headline, 'candidate headline'), candidate_type: oneOf(row.candidate_type, ['certified_educator','student'] as const, 'candidate type'), institution: nullableString(row.institution, 'student institution'), program: nullableString(row.program, 'student program'), expected_graduation_date: nullableString(row.expected_graduation_date, 'expected graduation date'), onboarding_completed_at: string(row.onboarding_completed_at, 'onboarding completion time'), certification_type: nullableString(row.certification_type, 'certification type'), certification_verification_status: oneOf(row.certification_verification_status, ['unverified','pending','verified','rejected'] as const, 'certification status'), certification_provenance: nullableOneOf(row.certification_provenance, ['manual','local_ocr'] as const, 'certification provenance'), certification_candidate_confirmed_at: nullableString(row.certification_candidate_confirmed_at, 'certification candidate confirmation time'), discoverable: true, experience_count: Number(row.experience_count), updated_at: string(row.updated_at, 'profile update time') }; }
const parseList = (value: unknown) => { if (!Array.isArray(value)) throw new MarketplaceApiError('The server returned an invalid candidate search.'); return value.map(parseDiscoverableCandidate); };
const parseInterest = (value: unknown): MarketplaceInterest => { const row = object(value, 'marketplace interest'); return { id: string(row.id, 'interest id'), profile_user_id: string(row.profile_user_id, 'interest profile'), job_id: string(row.job_id, 'interest job'), status: oneOf(row.status, ['requested'] as const, 'interest status'), message: nullableString(row.message, 'interest message'), created_at: string(row.created_at, 'interest creation time') }; };
const parseInterview = (value: unknown): InterviewRequest => { const row = object(value, 'interview request'); return { id: string(row.id, 'interview id'), application_id: string(row.application_id, 'interview application'), scheduled_at: string(row.scheduled_at, 'interview time'), location_or_link: string(row.location_or_link, 'interview location'), status: oneOf(row.status, ['requested'] as const, 'interview status') }; };
const parseCredentialNotification = (value: unknown): CredentialNotification => { const row = object(value, 'credential notification'); return { id: string(row.id, 'notification id'), credential_id: string(row.credential_id, 'credential id'), candidate_user_id: string(row.candidate_user_id, 'candidate user id'), candidate_name: string(row.candidate_name, 'candidate name'), previous_certificate_type: nullableString(row.previous_certificate_type, 'previous certificate type'), certificate_type: string(row.certificate_type, 'certificate type'), read_at: nullableString(row.read_at, 'notification read time'), created_at: string(row.created_at, 'notification creation time') }; };

export const marketplaceApi = {
  searchCandidates: async (city = '', signal?: AbortSignal) => { const query = new URLSearchParams(); if (city.trim()) query.set('city', city.trim()); const suffix = query.size ? `?${query}` : ''; return parseList(await apiRequest<unknown>(`/ats/marketplace/candidates${suffix}`, { signal })); },
  expressInterest: async (profileUserId: string, jobId: string, message?: string) => parseInterest(await apiRequest<unknown>('/ats/marketplace/interests', { method: 'POST', body: JSON.stringify({ profile_user_id: profileUserId, job_id: jobId, message: message?.trim() || null }) })),
  requestInterview: async (applicationId: string, scheduledAt: string, locationOrLink: string, timezone: string) => parseInterview(await apiRequest<unknown>(`/ats/marketplace/applications/${encodeURIComponent(applicationId)}/interviews`, { method: 'POST', body: JSON.stringify({ scheduled_at: scheduledAt, location_or_link: locationOrLink, timezone }) })),
  decideInterviewProposal: (interviewId: string, decision: 'accepted' | 'declined' | 'countered', scheduledAt?: string, locationOrLink?: string, timezone?: string) => apiRequest(`/ats/marketplace/interviews/${encodeURIComponent(interviewId)}/proposal-decision`, { method: 'POST', body: JSON.stringify({ decision, scheduled_at: scheduledAt || null, location_or_link: locationOrLink?.trim() || null, timezone: timezone || null }) }),
  credentialNotifications: async () => { const value = await apiRequest<unknown>('/ats/marketplace/credential-notifications'); if (!Array.isArray(value)) throw new MarketplaceApiError('The server returned invalid credential notifications.'); return value.map(parseCredentialNotification); },
  readCredentialNotification: (id: string) => apiRequest(`/ats/marketplace/credential-notifications/${encodeURIComponent(id)}/read`, { method: 'POST' }),
};
