"""Opt-in two-cluster PostgreSQL backup/restore proof under FORCE RLS."""

from __future__ import annotations

import os
from pathlib import Path

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

from scripts.backup_database import BackupContractError, create_backup
from scripts.restore_database import restore_and_verify

SOURCE_PORT = os.environ.get("BASIC_POSTGRES_BACKUP_SOURCE_PORT")
TARGET_PORT = os.environ.get("BASIC_POSTGRES_BACKUP_TARGET_PORT")
pytestmark = pytest.mark.skipif(
    not SOURCE_PORT or not TARGET_PORT,
    reason="requires two explicitly disposable PostgreSQL clusters",
)


def _url(port: str, user: str = "postgres") -> URL:
    return URL.create(
        "postgresql+psycopg",
        username=user,
        host="127.0.0.1",
        port=int(port),
        database="caresync",
    )


def _create_fixture(port: str, *, with_rows: bool) -> None:
    engine = create_engine(_url(port), isolation_level="AUTOCOMMIT")
    try:
        with engine.connect() as connection:
            connection.exec_driver_sql("DROP TABLE IF EXISTS protected_rows CASCADE")
            connection.exec_driver_sql("DROP TABLE IF EXISTS organizations CASCADE")
            connection.exec_driver_sql("DROP TABLE IF EXISTS alembic_version CASCADE")
            connection.exec_driver_sql(
                "CREATE TABLE alembic_version (version_num varchar(64) PRIMARY KEY)"
            )
            connection.exec_driver_sql("INSERT INTO alembic_version VALUES ('backup_fixture')")
            connection.exec_driver_sql(
                "CREATE TABLE organizations (id uuid PRIMARY KEY, name text NOT NULL)"
            )
            connection.exec_driver_sql(
                "CREATE TABLE protected_rows ("
                "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "organization_id uuid NOT NULL REFERENCES organizations(id), "
                "value text NOT NULL)"
            )
            connection.exec_driver_sql("ALTER TABLE protected_rows ENABLE ROW LEVEL SECURITY")
            connection.exec_driver_sql("ALTER TABLE protected_rows FORCE ROW LEVEL SECURITY")
            connection.exec_driver_sql(
                "CREATE POLICY protected_rows_tenant ON protected_rows "
                "USING (organization_id = NULLIF("
                "current_setting('app.current_organization_id', true), '')::uuid)"
            )
            if with_rows:
                connection.exec_driver_sql(
                    "INSERT INTO organizations VALUES "
                    "('11111111-1111-1111-1111-111111111111','One'),"
                    "('22222222-2222-2222-2222-222222222222','Two')"
                )
                connection.exec_driver_sql(
                    "INSERT INTO protected_rows (organization_id,value) VALUES "
                    "('11111111-1111-1111-1111-111111111111','alpha'),"
                    "('22222222-2222-2222-2222-222222222222','beta')"
                )
            else:
                connection.exec_driver_sql(
                    "INSERT INTO organizations VALUES "
                    "('99999999-9999-9999-9999-999999999999','stale')"
                )
                connection.exec_driver_sql(
                    "INSERT INTO protected_rows (organization_id,value) VALUES "
                    "('99999999-9999-9999-9999-999999999999','must disappear')"
                )
    finally:
        engine.dispose()


def _configure(monkeypatch: pytest.MonkeyPatch, port: str, user: str = "postgres") -> None:
    monkeypatch.setenv("DATABASE_TYPE", "postgres")
    monkeypatch.setenv("DATABASE_HOST", "127.0.0.1")
    monkeypatch.setenv("DATABASE_PORT", port)
    monkeypatch.setenv("DATABASE_USER", user)
    monkeypatch.setenv("DATABASE_PASSWORD", "")
    monkeypatch.setenv("DATABASE_NAME", "caresync")


def test_force_rls_backup_fails_closed_then_restores_exactly(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    assert SOURCE_PORT is not None and TARGET_PORT is not None
    assert int(SOURCE_PORT) not in {5432, 5433, 5434}
    assert int(TARGET_PORT) not in {5432, 5433, 5434}
    assert SOURCE_PORT != TARGET_PORT
    _create_fixture(SOURCE_PORT, with_rows=True)
    _create_fixture(TARGET_PORT, with_rows=False)

    source_admin = create_engine(_url(SOURCE_PORT), isolation_level="AUTOCOMMIT")
    try:
        with source_admin.connect() as connection:
            connection.execute(
                text(
                    "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles "
                    "WHERE rolname='backup_limited') THEN "
                    "DROP OWNED BY backup_limited; END IF; END $$"
                )
            )
            connection.execute(text("DROP ROLE IF EXISTS backup_limited"))
            connection.execute(text("CREATE ROLE backup_limited LOGIN NOSUPERUSER NOBYPASSRLS"))
            connection.execute(text("GRANT USAGE ON SCHEMA public TO backup_limited"))
            connection.execute(
                text("GRANT SELECT ON ALL TABLES IN SCHEMA public TO backup_limited")
            )
    finally:
        source_admin.dispose()

    _configure(monkeypatch, SOURCE_PORT, "backup_limited")
    with pytest.raises(BackupContractError, match="cannot bypass FORCE RLS"):
        create_backup(tmp_path / "rejected")

    _configure(monkeypatch, SOURCE_PORT)
    backup, manifest = create_backup(tmp_path / "accepted")
    _configure(monkeypatch, TARGET_PORT)
    confirmation = f"127.0.0.1:{TARGET_PORT}/caresync"
    monkeypatch.setenv("CARESYNC_RESTORE_CONFIRM_DISPOSABLE", confirmation)
    receipt = tmp_path / "receipts" / "restore.json"
    result = restore_and_verify(
        backup,
        manifest,
        prepare_empty_target=False,
        receipt_path=receipt,
    )

    assert result["tableCounts"] == {
        "alembic_version": 1,
        "organizations": 2,
        "protected_rows": 2,
    }
    assert result["totalRows"] == 5
    assert receipt.is_file()

    target = create_engine(_url(TARGET_PORT))
    try:
        with target.connect() as connection:
            assert connection.execute(
                text("SELECT value FROM protected_rows ORDER BY id")
            ).scalars().all() == ["alpha", "beta"]
            next_id = connection.execute(
                text(
                    "INSERT INTO protected_rows (organization_id,value) VALUES "
                    "('11111111-1111-1111-1111-111111111111','next') RETURNING id"
                )
            ).scalar_one()
            assert next_id == 3
    finally:
        target.dispose()
