import { useEffect, useState, type FormEvent } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowPathIcon, CheckCircleIcon, ExclamationTriangleIcon, KeyIcon, ShieldCheckIcon } from '@heroicons/react/24/outline';
import { ActionButton, Eyebrow } from '../../components/ui/Primitives';
import { oneTimeTokenFromHash, passwordErrors } from '../staff/staffModel';
import { staffApi } from '../staff/staffApi';
import type { PasswordResetPreview } from '../staff/types';
import { CredentialActions, CredentialCard, CredentialField, CredentialForm, CredentialNotice, CredentialPage, Summary } from './AccessCredentialStyles';

export default function PasswordResetPage() {
  const location = useLocation(); const token = oneTimeTokenFromHash(location.hash); const [preview, setPreview] = useState<PasswordResetPreview | null>(null); const [phase, setPhase] = useState<'loading'|'ready'|'error'|'saving'|'done'>('loading'); const [error, setError] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState('');
  useEffect(() => { if (!token) { setError('This password reset link is incomplete.'); setPhase('error'); return; } const controller = new AbortController(); staffApi.resetPreview(token, controller.signal).then((value) => { if (!controller.signal.aborted) { setPreview(value); setPhase('ready'); } }).catch((caught) => { if (!controller.signal.aborted) { setError(caught instanceof Error ? caught.message : 'This reset link is unavailable.'); setPhase('error'); } }); return () => controller.abort(); }, [token]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const errors = passwordErrors(password, confirmation); if (errors.length) { setError(errors.join(' ')); return; } setPhase('saving'); setError(''); try { await staffApi.completeReset(token, password); setPhase('done'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Your password could not be reset.'); setPhase('ready'); } };
  return <CredentialPage><CredentialCard $accent={phase === 'error' ? 'amber' : 'plasma'}><header><Eyebrow><ShieldCheckIcon width={14} /> CareSync credential recovery</Eyebrow><h1>Choose a new password.</h1><p>A one-time recovery link can change only the invited staff identity it was issued for.</p></header>{phase === 'loading' && <CredentialNotice><ArrowPathIcon /> Verifying this one-time reset link…</CredentialNotice>}{phase === 'error' && <><CredentialNotice $error role="alert"><ExclamationTriangleIcon /> {error}</CredentialNotice><CredentialActions><ActionButton as={Link} to="/login">Return to sign in</ActionButton></CredentialActions></>}{phase === 'done' && <><CredentialNotice><CheckCircleIcon /> Password changed. The reset link can no longer be used.</CredentialNotice><CredentialActions><ActionButton as={Link} to="/login" $variant="primary">Sign in</ActionButton></CredentialActions></>}{preview && (phase === 'ready' || phase === 'saving') && <><Summary><strong>{preview.email}</strong><span>{preview.organization_name}</span></Summary><CredentialForm onSubmit={submit}><CredentialField><span>New password</span><input required minLength={12} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /></CredentialField><CredentialField><span>Confirm new password</span><input required minLength={12} type="password" autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></CredentialField>{error && <CredentialNotice $error role="alert"><ExclamationTriangleIcon /> {error}</CredentialNotice>}<CredentialNotice><KeyIcon /> Use at least 12 characters. Existing passwords and expired links are rejected by the server.</CredentialNotice><CredentialActions><ActionButton type="submit" $variant="primary" disabled={phase === 'saving'}>{phase === 'saving' ? 'Saving…' : 'Set new password'}</ActionButton></CredentialActions></CredentialForm></>}</CredentialCard></CredentialPage>;
}
