import { useEffect, useState, type FormEvent } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowPathIcon, CheckCircleIcon, ExclamationTriangleIcon, KeyIcon, ShieldCheckIcon } from '@heroicons/react/24/outline';
import { useSession } from '../../auth/SessionContext';
import { ActionButton, Eyebrow, StatusChip } from '../../components/ui/Primitives';
import { oneTimeTokenFromHash, passwordErrors } from '../staff/staffModel';
import { staffApi } from '../staff/staffApi';
import type { StaffActivationPreview } from '../staff/types';
import { CredentialActions, CredentialCard, CredentialField, CredentialForm, CredentialNotice, CredentialPage, Summary } from './AccessCredentialStyles';

export default function StaffActivationPage() {
  const location = useLocation(); const token = oneTimeTokenFromHash(location.hash); const navigate = useNavigate(); const session = useSession();
  const [preview, setPreview] = useState<StaffActivationPreview | null>(null); const [phase, setPhase] = useState<'loading'|'ready'|'error'|'saving'>('loading'); const [error, setError] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState('');
  useEffect(() => { if (!token) { setError('This activation link is incomplete.'); setPhase('error'); return; } const controller = new AbortController(); staffApi.activationPreview(token, controller.signal).then((value) => { if (!controller.signal.aborted) { setPreview(value); setPhase('ready'); } }).catch((caught) => { if (!controller.signal.aborted) { setError(caught instanceof Error ? caught.message : 'This activation link is unavailable.'); setPhase('error'); } }); return () => controller.abort(); }, [token]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const errors = passwordErrors(password, confirmation); if (errors.length) { setError(errors.join(' ')); return; } setPhase('saving'); setError(''); try { await session.activateStaff(token, password); navigate('/dashboard', { replace: true }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Your account could not be activated.'); setPhase('ready'); } };
  return <CredentialPage><CredentialCard $accent={phase === 'error' ? 'amber' : 'cyan'}><header><Eyebrow><ShieldCheckIcon width={14} /> CareSync staff activation</Eyebrow><h1>Join your care workspace.</h1><p>Confirm the invitation and choose a private password. Your room access is already limited by the organization.</p></header>{phase === 'loading' && <CredentialNotice><ArrowPathIcon /> Verifying this one-time invitation…</CredentialNotice>}{phase === 'error' && <><CredentialNotice $error role="alert"><ExclamationTriangleIcon /> {error}</CredentialNotice><CredentialActions><ActionButton onClick={() => navigate('/login')}>Return to sign in</ActionButton></CredentialActions></>}{preview && phase !== 'loading' && phase !== 'error' && <><Summary><StatusChip $tone="info">{preview.role_name}</StatusChip><strong>{preview.first_name} {preview.last_name} · {preview.organization_name}</strong><span>{preview.email}</span><span>{preview.assigned_room_names.length ? `Assigned rooms: ${preview.assigned_room_names.join(', ')}` : 'Organization-wide access'}</span></Summary><CredentialForm onSubmit={submit}><CredentialField><span>Create password</span><input required minLength={12} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /></CredentialField><CredentialField><span>Confirm password</span><input required minLength={12} type="password" autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></CredentialField>{error && <CredentialNotice $error role="alert"><ExclamationTriangleIcon /> {error}</CredentialNotice>}<CredentialNotice><KeyIcon /> Use at least 12 characters. This activation link stops working after successful use.</CredentialNotice><CredentialActions><ActionButton type="submit" $variant="primary" disabled={phase === 'saving'}>{phase === 'saving' ? <><ArrowPathIcon /> Activating…</> : <><CheckCircleIcon /> Activate account</>}</ActionButton></CredentialActions></CredentialForm></>}</CredentialCard></CredentialPage>;
}
