"""Frozen CareSync Basic revision-zero schema and tenant policies.

Revision ID: 0001_basic_foundation
Revises: None
Create Date: 2026-07-14
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy import inspect

from alembic import op

revision = "0001_basic_foundation"
down_revision = None
branch_labels = None
depends_on = None

TENANT_TABLES = (
    "roles",
    "organization_onboarding",
    "facilities",
    "facility_programs",
    "rooms",
    "families",
    "guardians",
    "emergency_contacts",
    "children",
    "enrollments",
    "attendance_days",
    "attendance_intervals",
)
IMMUTABLE_TENANT_TABLES = ("attendance_events", "audit_events")


def _postgres_rls() -> None:
    org_setting = "NULLIF(current_setting('app.current_organization_id', true), '')::uuid"
    user_setting = "NULLIF(current_setting('app.current_user_id', true), '')::uuid"

    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organizations FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY organizations_tenant ON organizations "
        f"USING (id = {org_setting}) WITH CHECK (id = {org_setting})"
    )

    op.execute("ALTER TABLE organization_memberships ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organization_memberships FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY memberships_identity ON organization_memberships "
        f"USING (user_id = {user_setting} OR organization_id = {org_setting}) "
        f"WITH CHECK (user_id = {user_setting} OR organization_id = {org_setting})"
    )

    for table_name in TENANT_TABLES:
        op.execute(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY "{table_name}_tenant" ON "{table_name}" '
            f"USING (organization_id = {org_setting}) "
            f"WITH CHECK (organization_id = {org_setting})"
        )

    for table_name in IMMUTABLE_TENANT_TABLES:
        op.execute(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY "{table_name}_select" ON "{table_name}" FOR SELECT '
            f"USING (organization_id = {org_setting})"
        )
        op.execute(
            f'CREATE POLICY "{table_name}_insert" ON "{table_name}" FOR INSERT '
            f"WITH CHECK (organization_id = {org_setting})"
        )


def upgrade() -> None:
    bind = op.get_bind()
    existing = set(inspect(bind).get_table_names()) - {"alembic_version"}
    if existing:
        names = ", ".join(sorted(existing)[:10])
        raise RuntimeError(
            "CareSync Basic revision zero requires an empty database; "
            f"found existing tables: {names}"
        )

    # Frozen schema snapshot generated from the Basic model at revision creation.
    # Future model changes must be expressed in later revisions.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','active','suspended','archived')", name="ck_organizations_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_status"), "organizations", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "facilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("license_number", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("street_address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("province", sa.String(length=50), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("licensed_capacity", sa.Integer(), nullable=False),
        sa.Column("opening_time", sa.Time(), nullable=True),
        sa.Column("closing_time", sa.Time(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('draft','active','inactive')", name="ck_facilities_status"),
        sa.CheckConstraint("licensed_capacity >= 0", name="ck_facilities_capacity"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_facilities_org_id_id"),
        sa.UniqueConstraint("organization_id", "license_number", name="uq_facilities_org_license"),
    )
    op.create_index(
        op.f("ix_facilities_organization_id"), "facilities", ["organization_id"], unique=False
    )
    op.create_table(
        "families",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_number", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("additional_notes", sa.Text(), nullable=True),
        sa.Column("photo_consent", sa.Boolean(), nullable=False),
        sa.Column("field_trip_consent", sa.Boolean(), nullable=False),
        sa.Column("emergency_medical_consent", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','inactive','archived')", name="ck_families_status"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "file_number", name="uq_families_org_file_number"),
        sa.UniqueConstraint("organization_id", "id", name="uq_families_org_id_id"),
    )
    op.create_index(
        op.f("ix_families_organization_id"), "families", ["organization_id"], unique=False
    )
    op.create_table(
        "organization_onboarding",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_step", sa.String(length=50), nullable=False),
        sa.Column("completed_steps", sa.JSON(), nullable=False),
        sa.Column("draft", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','in_progress','complete')", name="ck_onboarding_status"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("organization_id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_roles_org_id_id"),
        sa.UniqueConstraint("organization_id", "key", name="uq_roles_org_key"),
    )
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id", "facility_id"],
            ["facilities.organization_id", "facilities.id"],
            name="fk_audit_events_org_facility",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_audit_events_org_id_id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_table(
        "children",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(length=30), nullable=True),
        sa.Column("age_group", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("health_care_number", sa.String(length=100), nullable=True),
        sa.Column("allergies", sa.Text(), nullable=True),
        sa.Column("medical_conditions", sa.Text(), nullable=True),
        sa.Column("medications", sa.Text(), nullable=True),
        sa.Column("immunization_up_to_date", sa.Boolean(), nullable=True),
        sa.Column("doctor_name", sa.String(length=255), nullable=True),
        sa.Column("doctor_phone", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "family_id"],
            ["families.organization_id", "families.id"],
            name="fk_children_org_family",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_children_org_id_id"),
    )
    op.create_index(op.f("ix_children_family_id"), "children", ["family_id"], unique=False)
    op.create_index(
        op.f("ix_children_organization_id"), "children", ["organization_id"], unique=False
    )
    op.create_table(
        "emergency_contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("relationship", sa.String(length=100), nullable=False),
        sa.Column("cell_phone", sa.String(length=30), nullable=False),
        sa.Column("home_phone", sa.String(length=30), nullable=True),
        sa.Column("authorized_pickup", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "family_id"],
            ["families.organization_id", "families.id"],
            name="fk_contacts_org_family",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_contacts_org_id_id"),
    )
    op.create_index(
        op.f("ix_emergency_contacts_family_id"), "emergency_contacts", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_emergency_contacts_organization_id"),
        "emergency_contacts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "facility_programs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("program_type", sa.String(length=100), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("minimum_age_months", sa.Integer(), nullable=True),
        sa.Column("maximum_age_months", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity >= 0", name="ck_programs_capacity"),
        sa.ForeignKeyConstraint(
            ["organization_id", "facility_id"],
            ["facilities.organization_id", "facilities.id"],
            name="fk_programs_org_facility",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "facility_id", "name", name="uq_programs_facility_name"
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_programs_org_id_id"),
    )
    op.create_index(
        op.f("ix_facility_programs_facility_id"), "facility_programs", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_facility_programs_organization_id"),
        "facility_programs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "guardians",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("relationship", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("cell_phone", sa.String(length=30), nullable=False),
        sa.Column("home_phone", sa.String(length=30), nullable=True),
        sa.Column("work_phone", sa.String(length=30), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("authorized_pickup", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "family_id"],
            ["families.organization_id", "families.id"],
            name="fk_guardians_org_family",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_guardians_org_id_id"),
    )
    op.create_index(op.f("ix_guardians_family_id"), "guardians", ["family_id"], unique=False)
    op.create_index(
        op.f("ix_guardians_organization_id"), "guardians", ["organization_id"], unique=False
    )
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('invited','active','suspended','revoked')", name="ck_memberships_status"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "role_id"],
            ["roles.organization_id", "roles.id"],
            name="fk_memberships_org_role",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_memberships_org_id_id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_memberships_org_user"),
    )
    op.create_index(
        op.f("ix_organization_memberships_organization_id"),
        "organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_user_id"),
        "organization_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("age_group", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity > 0", name="ck_rooms_capacity"),
        sa.ForeignKeyConstraint(
            ["organization_id", "facility_id"],
            ["facilities.organization_id", "facilities.id"],
            name="fk_rooms_org_facility",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "program_id"],
            ["facility_programs.organization_id", "facility_programs.id"],
            name="fk_rooms_org_program",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "facility_id", "name", name="uq_rooms_facility_name"
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_rooms_org_id_id"),
    )
    op.create_index(op.f("ix_rooms_facility_id"), "rooms", ["facility_id"], unique=False)
    op.create_index(op.f("ix_rooms_organization_id"), "rooms", ["organization_id"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("room_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','paused','ended')", name="ck_enrollments_status"
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date", name="ck_enrollment_dates"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "child_id"],
            ["children.organization_id", "children.id"],
            name="fk_enrollments_org_child",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "facility_id"],
            ["facilities.organization_id", "facilities.id"],
            name="fk_enrollments_org_facility",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "program_id"],
            ["facility_programs.organization_id", "facility_programs.id"],
            name="fk_enrollments_org_program",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "room_id"],
            ["rooms.organization_id", "rooms.id"],
            name="fk_enrollments_org_room",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "facility_id",
            "child_id",
            "id",
            name="uq_enrollments_attendance_identity",
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_enrollments_org_id_id"),
    )
    op.create_index(op.f("ix_enrollments_child_id"), "enrollments", ["child_id"], unique=False)
    op.create_index(
        op.f("ix_enrollments_facility_id"), "enrollments", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollments_organization_id"), "enrollments", ["organization_id"], unique=False
    )
    op.create_table(
        "attendance_days",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("absence_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('present','absent')", name="ck_attendance_days_status"),
        sa.CheckConstraint("version > 0", name="ck_attendance_days_version"),
        sa.ForeignKeyConstraint(
            ["organization_id", "child_id"],
            ["children.organization_id", "children.id"],
            name="fk_attendance_days_org_child",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "facility_id", "child_id", "enrollment_id"],
            [
                "enrollments.organization_id",
                "enrollments.facility_id",
                "enrollments.child_id",
                "enrollments.id",
            ],
            name="fk_attendance_days_enrollment_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "facility_id"],
            ["facilities.organization_id", "facilities.id"],
            name="fk_attendance_days_org_facility",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "facility_id",
            "child_id",
            "service_date",
            name="uq_attendance_days_child_date",
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_attendance_days_org_id_id"),
    )
    op.create_index(
        op.f("ix_attendance_days_child_id"), "attendance_days", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_days_facility_id"), "attendance_days", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_days_organization_id"),
        "attendance_days",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_days_service_date"), "attendance_days", ["service_date"], unique=False
    )
    op.create_table(
        "attendance_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("attendance_day_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id", "attendance_day_id"],
            ["attendance_days.organization_id", "attendance_days.id"],
            name="fk_attendance_events_org_day",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_attendance_events_org_id_id"),
    )
    op.create_index(
        op.f("ix_attendance_events_attendance_day_id"),
        "attendance_events",
        ["attendance_day_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_events_organization_id"),
        "attendance_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "attendance_intervals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("attendance_day_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checked_out_at IS NULL OR checked_out_at >= checked_in_at",
            name="ck_attendance_interval_order",
        ),
        sa.CheckConstraint("sequence > 0", name="ck_attendance_intervals_sequence"),
        sa.ForeignKeyConstraint(
            ["organization_id", "attendance_day_id"],
            ["attendance_days.organization_id", "attendance_days.id"],
            name="fk_attendance_intervals_org_day",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "attendance_day_id",
            "sequence",
            name="uq_attendance_intervals_day_sequence",
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_attendance_intervals_org_id_id"),
    )
    op.create_index(
        op.f("ix_attendance_intervals_attendance_day_id"),
        "attendance_intervals",
        ["attendance_day_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_intervals_organization_id"),
        "attendance_intervals",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    if bind.dialect.name == "postgresql":
        _postgres_rls()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_attendance_intervals_organization_id"), table_name="attendance_intervals"
    )
    op.drop_index(
        op.f("ix_attendance_intervals_attendance_day_id"), table_name="attendance_intervals"
    )
    op.drop_table("attendance_intervals")
    op.drop_index(op.f("ix_attendance_events_organization_id"), table_name="attendance_events")
    op.drop_index(op.f("ix_attendance_events_attendance_day_id"), table_name="attendance_events")
    op.drop_table("attendance_events")
    op.drop_index(op.f("ix_attendance_days_service_date"), table_name="attendance_days")
    op.drop_index(op.f("ix_attendance_days_organization_id"), table_name="attendance_days")
    op.drop_index(op.f("ix_attendance_days_facility_id"), table_name="attendance_days")
    op.drop_index(op.f("ix_attendance_days_child_id"), table_name="attendance_days")
    op.drop_table("attendance_days")
    op.drop_index(op.f("ix_enrollments_organization_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_facility_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_child_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_rooms_organization_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_facility_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(
        op.f("ix_organization_memberships_user_id"), table_name="organization_memberships"
    )
    op.drop_index(
        op.f("ix_organization_memberships_organization_id"), table_name="organization_memberships"
    )
    op.drop_table("organization_memberships")
    op.drop_index(op.f("ix_guardians_organization_id"), table_name="guardians")
    op.drop_index(op.f("ix_guardians_family_id"), table_name="guardians")
    op.drop_table("guardians")
    op.drop_index(op.f("ix_facility_programs_organization_id"), table_name="facility_programs")
    op.drop_index(op.f("ix_facility_programs_facility_id"), table_name="facility_programs")
    op.drop_table("facility_programs")
    op.drop_index(op.f("ix_emergency_contacts_organization_id"), table_name="emergency_contacts")
    op.drop_index(op.f("ix_emergency_contacts_family_id"), table_name="emergency_contacts")
    op.drop_table("emergency_contacts")
    op.drop_index(op.f("ix_children_organization_id"), table_name="children")
    op.drop_index(op.f("ix_children_family_id"), table_name="children")
    op.drop_table("children")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("organization_onboarding")
    op.drop_index(op.f("ix_families_organization_id"), table_name="families")
    op.drop_table("families")
    op.drop_index(op.f("ix_facilities_organization_id"), table_name="facilities")
    op.drop_table("facilities")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_status"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
