import type { RoomDailyClosePreview } from './dailyCloseApi';

export const dailyClosePreviewFixture = {
  organization_id: 'org-1',
  facility_id: 'facility-1',
  facility_name: 'Main Centre',
  facility_timezone: 'America/Edmonton',
  room_id: 'room-1',
  room_name: 'Infant North',
  service_date: '2026-07-15',
  generated_at: '2026-07-15T18:00:00Z',
  totals: {
    child_count: 1,
    attendance_state_counts: { not_recorded: 0, on_site: 1, checked_out: 0, no_show: 0 },
    accumulated_minutes: 120,
    currently_on_site: 1,
    care_counts: { feeding: 1, diaper: 2, toilet: 0, sleep: 1, mood: 1, activity: 3 },
    open_sleep: 1,
    medication_administration_counts: { administered: 2, refused: 1, omitted: 1 },
    incident_status_counts: { draft: 1, under_review: 1, finalized: 2 },
    attention_flag_counts: {
      open_sleep: 1,
      medication_refused: 1,
      medication_omitted: 1,
      incident_draft: 1,
      incident_under_review: 1,
    },
  },
  children: [{
    child_id: 'child-1',
    child_name: 'Noor Ali',
    profile_photo_url: '/api/v1/children/child-1/photo',
    enrollment_id: 'enrollment-1',
    attendance_day_id: 'day-1',
    attendance_state: 'on_site',
    first_check_in_at: '2026-07-15T16:00:00Z',
    last_checkout_at: null,
    accumulated_minutes: 120,
    currently_on_site: true,
    care_counts: { feeding: 1, diaper: 2, toilet: 0, sleep: 1, mood: 1, activity: 3 },
    open_sleep: true,
    most_recent_care_at: '2026-07-15T17:20:00Z',
    medication_administration_counts: { administered: 2, refused: 1, omitted: 1 },
    most_recent_medication_at: '2026-07-15T17:30:00Z',
    incident_status_counts: { draft: 1, under_review: 1, finalized: 2 },
    most_recent_incident_at: '2026-07-15T17:40:00Z',
    attention_flags: [
      'open_sleep',
      'medication_refused',
      'medication_omitted',
      'incident_draft',
      'incident_under_review',
    ],
  }],
} satisfies RoomDailyClosePreview;
