import { ApiError, apiRequest, getSelectedOrganizationId } from '../../api/client';
import { isProgramType } from '../../models/programTypes';
import type { BasicOrganization, FacilityRecord, OnboardingResponse, OnboardingStep, ProgramRecord, RoomRecord } from './types';

const object = (value: unknown, label: string): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new ApiError(0, `The server returned an invalid ${label}.`); return value as Record<string, unknown>; };
const text = (value: unknown, label: string) => { if (typeof value !== 'string' || !value.trim()) throw new ApiError(0, `The server returned an invalid ${label}.`); return value; };
const nullableText = (value: unknown, label: string) => value == null ? null : text(value, label);
const integer = (value: unknown, label: string) => { if (!Number.isInteger(value) || Number(value) < 0) throw new ApiError(0, `The server returned an invalid ${label}.`); return Number(value); };
const bool = (value: unknown, label: string) => { if (typeof value !== 'boolean') throw new ApiError(0, `The server returned an invalid ${label}.`); return value; };
const selected = (organizationId: string) => { const expected = getSelectedOrganizationId(); if (!expected || expected !== organizationId) throw new ApiError(403, 'Onboarding crossed the selected organization boundary.'); return organizationId; };

export function parseOnboardingOrganization(value: unknown): BasicOrganization { const row = object(value, 'onboarding organization'); const preferences = object(row.preferences, 'organization preferences'); return { id: selected(text(row.id, 'organization id')), name: text(row.name, 'organization name'), legal_name: nullableText(row.legal_name, 'organization legal name'), status: text(row.status, 'organization status'), email: nullableText(row.email, 'organization email'), phone: nullableText(row.phone, 'organization phone'), timezone: text(row.timezone, 'organization timezone'), preferences }; }
export function parseOnboardingFacility(value: unknown): FacilityRecord { const row = object(value, 'onboarding facility'); const status = text(row.status, 'facility status'); if (!['draft','active','inactive'].includes(status)) throw new ApiError(0, 'The server returned an unsupported facility status.'); return { id: text(row.id, 'facility id'), organization_id: selected(text(row.organization_id, 'facility organization')), name: text(row.name, 'facility name'), license_number: nullableText(row.license_number, 'facility license'), status: status as FacilityRecord['status'], email: nullableText(row.email, 'facility email'), phone: nullableText(row.phone, 'facility phone'), street_address: nullableText(row.street_address, 'facility address'), city: nullableText(row.city, 'facility city'), province: text(row.province, 'facility province'), postal_code: nullableText(row.postal_code, 'facility postal code'), timezone: text(row.timezone, 'facility timezone'), licensed_capacity: integer(row.licensed_capacity, 'facility capacity'), opening_time: nullableText(row.opening_time, 'opening time'), closing_time: nullableText(row.closing_time, 'closing time') }; }
export function parseOnboardingProgram(value: unknown): ProgramRecord { const row = object(value, 'onboarding program'); const organizationId = selected(text(row.organization_id, 'program organization')); const programType = row.program_type == null ? null : row.program_type; if (programType !== null && !isProgramType(programType)) throw new ApiError(0, 'The server returned an unsupported program type.'); return { id: text(row.id, 'program id'), organization_id: organizationId, facility_id: text(row.facility_id, 'program facility'), name: text(row.name, 'program name'), program_type: programType, capacity: integer(row.capacity, 'program capacity'), minimum_age_months: row.minimum_age_months == null ? null : integer(row.minimum_age_months, 'minimum age'), maximum_age_months: row.maximum_age_months == null ? null : integer(row.maximum_age_months, 'maximum age'), is_active: bool(row.is_active, 'program status') }; }
export function parseOnboardingRoom(value: unknown): RoomRecord { const row = object(value, 'onboarding room'); return { id: text(row.id, 'room id'), organization_id: selected(text(row.organization_id, 'room organization')), facility_id: text(row.facility_id, 'room facility'), program_id: nullableText(row.program_id, 'room program'), name: text(row.name, 'room name'), capacity: integer(row.capacity, 'room capacity'), age_group: nullableText(row.age_group, 'room age group'), is_active: bool(row.is_active, 'room status') }; }
export function parseOnboardingResponse(value: unknown): OnboardingResponse { const row = object(value, 'onboarding workspace'); const organizationId = selected(text(row.organization_id, 'onboarding organization')); const status = text(row.status, 'onboarding status'); const current = text(row.current_step, 'onboarding step'); const steps = Array.isArray(row.completed_steps) ? row.completed_steps.map((step) => text(step, 'completed step')) : []; if (!['draft','in_progress','complete'].includes(status) || !['organization','facility','rooms','review','complete'].includes(current) || steps.some((step) => !['organization','facility','rooms','review'].includes(step))) throw new ApiError(0, 'The server returned an unsupported onboarding state.'); const organization = parseOnboardingOrganization(row.organization); const facilities = Array.isArray(row.facilities) ? row.facilities.map(parseOnboardingFacility) : []; if (organization.id !== organizationId || facilities.some((facility) => facility.organization_id !== organizationId)) throw new ApiError(403, 'Onboarding records crossed the active organization boundary.'); return { organization_id: organizationId, status: status as OnboardingResponse['status'], current_step: current as OnboardingResponse['current_step'], completed_steps: steps as OnboardingStep[], draft: object(row.draft, 'onboarding draft'), completed_at: nullableText(row.completed_at, 'onboarding completion'), organization, facilities }; }

const parseList = <T,>(value: unknown, label: string, parser: (item: unknown) => T) => { if (!Array.isArray(value)) throw new ApiError(0, `The server returned invalid ${label}.`); return value.map(parser); };
export const onboardingApi = {
  get: async (signal?: AbortSignal) => parseOnboardingResponse(await apiRequest<unknown>('/onboarding', { signal })),
  save: async (payload: { current_step?: OnboardingStep; completed_steps?: OnboardingStep[]; draft?: Record<string, unknown> }) => parseOnboardingResponse(await apiRequest<unknown>('/onboarding', { method: 'PATCH', body: JSON.stringify(payload) })),
  complete: async () => parseOnboardingResponse(await apiRequest<unknown>('/onboarding/complete', { method: 'POST' })),
  updateOrganization: async (payload: Record<string, unknown>) => parseOnboardingOrganization(await apiRequest<unknown>('/organization', { method: 'PATCH', body: JSON.stringify(payload) })),
  programs: async (facilityId: string, signal?: AbortSignal) => parseList(await apiRequest<unknown>(`/programs?facility_id=${encodeURIComponent(facilityId)}`, { signal }), 'programs', parseOnboardingProgram),
  createProgram: async (payload: Record<string, unknown>) => parseOnboardingProgram(await apiRequest<unknown>('/programs', { method: 'POST', body: JSON.stringify(payload) })),
  updateProgram: async (id: string, payload: Record<string, unknown>) => parseOnboardingProgram(await apiRequest<unknown>(`/programs/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(payload) })),
  rooms: async (facilityId: string, signal?: AbortSignal) => parseList(await apiRequest<unknown>(`/rooms?facility_id=${encodeURIComponent(facilityId)}`, { signal }), 'rooms', parseOnboardingRoom),
  createRoom: async (payload: Record<string, unknown>) => parseOnboardingRoom(await apiRequest<unknown>('/rooms', { method: 'POST', body: JSON.stringify(payload) })),
  updateRoom: async (id: string, payload: Record<string, unknown>) => parseOnboardingRoom(await apiRequest<unknown>(`/rooms/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(payload) })),
  createFacility: async (payload: Record<string, unknown>) => parseOnboardingFacility(await apiRequest<unknown>('/facilities', { method: 'POST', body: JSON.stringify(payload) })),
  updateFacility: async (id: string, payload: Record<string, unknown>) => parseOnboardingFacility(await apiRequest<unknown>(`/facilities/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(payload) })),
};
